version: '3.8'

services:
  server:
    image: postgrest/postgrest:v12.0.3
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:mysecretpassword@db:5432/postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMAS: api
    depends_on:
      - db
    networks:
      - pgrest_net
  db:
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    networks:
      - pgrest_net
    volumes:
      - ./scripts:/home/scripts

networks:
  pgrest_net:
    driver: bridge